// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var app;

  app = angular.module('ngOughts', ['ng']);

  app.controller("BoardCtrl", function($scope, Board) {
    return $scope.board = new Board;
  });

}).call(this);
